cvc:
  canvas:
    # Specify the complete hostname for the Canvas instance
    host: INSITUTION.test.instructure.com

    # Specify the account ID
    accountId: 1

    # Provide an API token for an account authorization to import SIS data
    apiToken: API_TOKEN_HERE

  cross-enrollment:
    # Specify the input directory with cross-enrollment files for Canvas
    # Glob patterns are supported
    inputDirectory: 'colleague-input-dir/canvas*.csv'

  sis:
    # Specify the SIS type (banner, colleague, peoplesoft)
    type: colleague