cvc:
  canvas:
    # Specify the complete hostname for the Canvas instance
    host: INSITUTION.test.instructure.com

    # Specify the account ID
    accountId: 1

    # Provide an API token for an account authorization to import SIS data
    apiToken: API_TOKEN_HERE

  sis:
    # Specify the SIS type (banner, colleague, peoplesoft)
    type: colleague

    # Specify the input file with cross-enrollments for Canvas
    canvasInputFile: /tmp/canvas.csv