cvc:
  sis:
    type: oracle
    properties:
      # Specify the JDBC URL to your database instance
      url: "jdbc:oracle:thin:@HOST:PORT/SERVICE"

      # Specify the username to connect as
      user: "USER"

      # Specify the credential to authenticate
      password: "PASSWORD"