#
# Default SIS configuration applied when the Banner profile is active
#
cvc:
  logins:
    sisQuery: |
      select
        studentid as "user_id",
        studentid as "login_id",
        homesisuserid as "existing_user_id",
        canvasrootaccount as "root_account"
      from
        niccrsxchng.n_stag_canvas